version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: aspire_db
    ports:
      - "5432:5432"
  
  api:
    build: .
    ports:
      - "5491:5491"
    environment:
      DATABASE_URL: postgres://user:password@db:5432/aspire_db
      JWT_SECRET: secret
    depends_on:
      - db
